# .tflint.hcl — generated by startup scaffolder
# Source: context/governance.md → Functional + Secure invariants for IaC
# {{PROJECT_NAME}}

config {
  call_module_type = "all"
  force            = false
}

plugin "terraform" {
  enabled = true
  preset  = "recommended"
}

# {{IF_AZURE}}
plugin "azurerm" {
  enabled = true
  version = "0.27.0"
  source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
}
# {{/IF_AZURE}}

# {{IF_AWS}}
plugin "aws" {
  enabled = true
  version = "0.32.0"
  source  = "github.com/terraform-linters/tflint-ruleset-aws"
}
# {{/IF_AWS}}

# {{IF_GCP}}
plugin "google" {
  enabled = true
  version = "0.30.0"
  source  = "github.com/terraform-linters/tflint-ruleset-google"
}
# {{/IF_GCP}}

# Naming conventions (customize per organization)
rule "terraform_naming_convention" {
  enabled = true
  format  = "snake_case"
}

rule "terraform_required_version"   { enabled = true }
rule "terraform_required_providers" { enabled = true }
rule "terraform_unused_declarations"{ enabled = true }
rule "terraform_documented_outputs" { enabled = true }
rule "terraform_documented_variables"{ enabled = true }
rule "terraform_typed_variables"    { enabled = true }
rule "terraform_module_pinned_source"{ enabled = true }
